version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hexo-all-minifier
    versions:
    - 0.5.7
  - dependency-name: hexo-deployer-git
    versions:
    - 3.0.0
- package-ecosystem: npm
  directory: "/themes/sagiri"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.27.1
    - 5.28.0
    - 5.30.0
    - 5.31.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.8
    - 7.13.9
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
    - 4.6.0
  - dependency-name: gsap
    versions:
    - 3.6.1
  - dependency-name: leancloud-storage
    versions:
    - 4.10.0
    - 4.10.1
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
