language: node_js
node_js: lts/*
install:
- yarn
before_script:

script:
- hexo clean
- hexo g
after_script:


branches:
  only:
  - hexo
env:
  global:
  - GH_REF: github.com/EGo14T/ego14t.github.io.git
cache:

before_install:
- openssl aes-256-cbc -K $encrypted_09fcd4f45c48_key -iv $encrypted_09fcd4f45c48_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- ssh git@${IPadress} -o StrictHostKeyChecking=no 'cd / && ll'

after_success:


addons:
  ssh_known_hosts: 49.232.14.91
