language: node_js
node_js: lts/*
install:
- yarn
before_script:
- cd themes/sagiri
- yarn
- cd ../..
script:
- hexo clean
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "EGo14T"
- git config user.email "974412906@qq.com"
- git add .
- git commit -m "Update docs with TRAVIS-CI"
- git push --set-upstream git@${IPadress}:/srv/gitrepo/myblog.git master
- git push --force --quiet "https://${EGo1ST}@${GH_REF}" master:master
branches:
  only:
  - hexo
env:
  global:
  - GH_REF: github.com/EGo14T/ego14t.github.io.git
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_09fcd4f45c48_key -iv $encrypted_09fcd4f45c48_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
#- ssh git@${IP} -o StrictHostKeyChecking=no 'git --version'
addons:
  ssh_known_hosts: 49.232.14.91
